# Generated by Django 2.2.7 on 2019-11-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImdbId', models.TextField(default='tt', unique=True)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField(null=True)),
                ('Year', models.TextField()),
                ('Rating', models.TextField(null=True)),
                ('Companies', models.TextField(null=True)),
                ('Country', models.TextField(null=True)),
                ('Language', models.TextField(null=True)),
                ('Duration', models.FloatField(null=True)),
                ('Directors', models.TextField(null=True)),
                ('Writers', models.TextField(null=True)),
                ('Actors', models.TextField(null=True)),
                ('Genres', models.TextField(null=True)),
                ('Synopsis', models.TextField(null=True)),
                ('Budget', models.TextField(null=True)),
                ('GrossUs', models.IntegerField(null=True)),
                ('GrossWorldwide', models.IntegerField(null=True)),
                ('Score', models.FloatField(null=True)),
                ('Votes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField(unique=True)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField()),
                ('Year', models.TextField()),
                ('Rating', models.TextField(null=True)),
                ('Companies', models.TextField(null=True)),
                ('Country', models.TextField(null=True)),
                ('Language', models.TextField(null=True)),
                ('RunTime', models.IntegerField(null=True)),
                ('Crew', models.TextField(null=True)),
                ('Cast', models.TextField(null=True)),
                ('Poster', models.TextField(null=True)),
                ('Genres', models.TextField(null=True)),
                ('Synopsis', models.TextField(null=True)),
                ('Budget', models.IntegerField(null=True)),
                ('Gross', models.IntegerField(null=True)),
                ('ScoreImdb', models.FloatField(null=True)),
                ('VotesImdb', models.IntegerField(null=True)),
                ('Indeces', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDB_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TmdbId', models.IntegerField(default=-1, unique=True)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField()),
                ('Year', models.TextField()),
                ('Companies', models.TextField(null=True)),
                ('Country', models.TextField(null=True)),
                ('Language', models.TextField()),
                ('RunTime', models.FloatField(null=True)),
                ('Crew', models.TextField(null=True)),
                ('Cast', models.TextField(null=True)),
                ('Poster', models.TextField(null=True)),
                ('Genres', models.TextField(null=True)),
                ('Collection', models.TextField(null=True)),
                ('Synopsis', models.TextField(null=True)),
                ('Budget', models.FloatField(null=True)),
                ('Gross', models.FloatField(null=True)),
                ('Score', models.TextField()),
                ('Votes', models.TextField()),
                ('ImdbId', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField()),
                ('Service', models.TextField()),
                ('ServiceKey', models.TextField()),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reelgood_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Year', models.TextField()),
                ('Rating', models.TextField(null=True)),
                ('Country', models.TextField(null=True)),
                ('Duration', models.FloatField(null=True)),
                ('Poster', models.TextField()),
                ('Genres', models.TextField(null=True)),
                ('Tags', models.TextField(null=True)),
                ('Synopsis', models.TextField()),
                ('ImdbScore', models.FloatField(null=True)),
                ('RtScore', models.TextField(null=True)),
                ('Services', models.TextField()),
            ],
            options={
                'unique_together': {('Title', 'Year')},
            },
        ),
    ]
