# Generated by Django 2.2.7 on 2019-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imdb_ID', models.IntegerField(default=0)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField()),
                ('Year', models.TextField()),
                ('Rating', models.TextField()),
                ('Companies', models.TextField()),
                ('Country', models.TextField()),
                ('Language', models.TextField()),
                ('RunTime', models.IntegerField(default=0)),
                ('Crew', models.TextField()),
                ('Cast', models.TextField()),
                ('Genres', models.TextField()),
                ('Synopsis', models.TextField()),
                ('Budget', models.IntegerField(default=0)),
                ('Gross_US', models.IntegerField(default=0)),
                ('Gross', models.IntegerField(default=0)),
                ('Score', models.FloatField()),
                ('Votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField(default=0)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField()),
                ('Year', models.TextField()),
                ('Rating', models.TextField()),
                ('Companies', models.TextField()),
                ('Country', models.TextField()),
                ('Language', models.TextField()),
                ('RunTime', models.IntegerField(default=0)),
                ('Crew', models.TextField()),
                ('Cast', models.TextField()),
                ('Poster', models.TextField()),
                ('Genres', models.TextField()),
                ('Collection', models.TextField()),
                ('Synopsis', models.TextField()),
                ('Budget', models.IntegerField(default=0)),
                ('Gross', models.IntegerField(default=0)),
                ('Scores', models.TextField()),
                ('Indeces', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieDB_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField(default=0)),
                ('Title', models.TextField()),
                ('OriginalTitle', models.TextField()),
                ('Year', models.TextField()),
                ('Companies', models.TextField()),
                ('Country', models.TextField()),
                ('Language', models.TextField()),
                ('RunTime', models.IntegerField(default=0)),
                ('Crew', models.TextField()),
                ('Cast', models.TextField()),
                ('Poster', models.TextField()),
                ('Genres', models.TextField()),
                ('Collection', models.TextField()),
                ('Synopsis', models.TextField()),
                ('Budget', models.IntegerField(default=0)),
                ('Gross', models.IntegerField(default=0)),
                ('Score', models.TextField()),
                ('Votes', models.TextField()),
                ('ImdbID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reelgood_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reelgood_ID', models.TextField()),
                ('Title', models.TextField()),
                ('Year', models.TextField()),
                ('Rating', models.TextField()),
                ('Country', models.TextField()),
                ('RunTime', models.IntegerField(default=0)),
                ('Poster', models.TextField()),
                ('Genres', models.TextField()),
                ('Tags', models.TextField()),
                ('Synopsis', models.TextField()),
                ('ImdbScore', models.FloatField(default=0)),
                ('RTScore', models.IntegerField(default=0)),
                ('Services', models.TextField()),
            ],
        ),
    ]
