# Generated by Django 2.2.7 on 2019-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField()),
                ('User', models.TextField()),
                ('Vote', models.IntegerField()),
            ],
        ),
    ]
