# Generated by Django 2.2.7 on 2019-11-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedb_load',
            old_name='ImdbID',
            new_name='ImdbId',
        ),
        migrations.RenameField(
            model_name='moviedb_load',
            old_name='Movie_ID',
            new_name='TmdbId',
        ),
    ]
