# Generated by Django 2.2.7 on 2019-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_uservotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Score',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Votes',
            field=models.TextField(null=True),
        ),
    ]
