# Generated by Django 2.2.7 on 2019-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191123_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Gross',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='RunTime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='TmdbId',
            field=models.IntegerField(),
        ),
    ]
