# Generated by Django 2.2.7 on 2019-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191123_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Gross',
            field=models.IntegerField(null=True),
        ),
    ]
