# Generated by Django 2.2.7 on 2019-11-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191123_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Collection',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Gross',
            field=models.FloatField(),
        ),
    ]
