# Generated by Django 2.2.7 on 2019-12-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191203_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecommendations',
            old_name='Movie_ID',
            new_name='Movie_FK',
        ),
        migrations.RenameField(
            model_name='userrecommendations',
            old_name='RecLevel',
            new_name='RecomLevel',
        ),
        migrations.AlterUniqueTogether(
            name='uservotes',
            unique_together={('Movie_ID', 'User')},
        ),
    ]
