# Generated by Django 2.2.7 on 2019-11-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191123_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Budget',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Gross',
            field=models.FloatField(null=True),
        ),
    ]
