# Generated by Django 2.2.7 on 2019-12-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191203_0256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecommendations',
            unique_together={('Movie_FK', 'User')},
        ),
    ]
