# Generated by Django 2.2.7 on 2019-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191123_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Companies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='Country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='ImdbId',
            field=models.TextField(null=True),
        ),
    ]
