# Generated by Django 2.2.7 on 2019-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20191123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='RunTime',
            field=models.FloatField(null=True),
        ),
    ]
