# Generated by Django 2.2.7 on 2019-12-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20191214_0234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecommendations',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrecommendations',
            name='Movie_FK',
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
        migrations.DeleteModel(
            name='UserRecommendations',
        ),
    ]
