# Generated by Django 2.2.7 on 2019-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20191123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb_load',
            name='Cast',
            field=models.TextField(null=True),
        ),
    ]
