# Generated by Django 2.2.7 on 2019-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20191123_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelgood_load',
            old_name='Reelgood_ID',
            new_name='Reelgood_Id',
        ),
        migrations.RemoveField(
            model_name='reelgood_load',
            name='RTScore',
        ),
        migrations.RemoveField(
            model_name='reelgood_load',
            name='RunTime',
        ),
        migrations.AddField(
            model_name='reelgood_load',
            name='Duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reelgood_load',
            name='RtScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='Country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='Genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='ImdbScore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='Rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='Tags',
            field=models.TextField(null=True),
        ),
    ]
