# Generated by Django 2.2.7 on 2019-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20191123_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelgood_load',
            name='RtScore',
            field=models.TextField(null=True),
        ),
    ]
