# Generated by Django 2.2.7 on 2019-11-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20191123_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdb_load',
            old_name='Imdb_ID',
            new_name='ImdbId',
        ),
    ]
