# Generated by Django 2.2.7 on 2019-11-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20191123_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdb_load',
            name='RunTime',
        ),
        migrations.AddField(
            model_name='imdb_load',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
    ]
