# Generated by Django 2.2.7 on 2019-11-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20191123_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imdb_load',
            old_name='Cast',
            new_name='Directors',
        ),
        migrations.RemoveField(
            model_name='imdb_load',
            name='Crew',
        ),
        migrations.RemoveField(
            model_name='imdb_load',
            name='Gross',
        ),
        migrations.RemoveField(
            model_name='imdb_load',
            name='Gross_US',
        ),
        migrations.AddField(
            model_name='imdb_load',
            name='Actors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imdb_load',
            name='GrossUs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imdb_load',
            name='GrossWorldwide',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imdb_load',
            name='Writers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Companies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='ImdbId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='OriginalTitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Votes',
            field=models.IntegerField(null=True),
        ),
    ]
