# Generated by Django 2.2.7 on 2019-11-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20191123_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb_load',
            name='ImdbId',
            field=models.TextField(),
        ),
    ]
