# Generated by Django 2.2.7 on 2019-11-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20191123_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb_load',
            name='Budget',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb_load',
            name='Duration',
            field=models.FloatField(null=True),
        ),
    ]
