# Generated by Django 2.2.7 on 2019-11-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20191123_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb_load',
            name='ImdbId',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='moviedb_load',
            name='TmdbId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='reelgood_load',
            name='Reelgood_Id',
            field=models.TextField(unique=True),
        ),
    ]
