# Generated by Django 2.2.7 on 2019-11-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20191123_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reelgood_load',
            unique_together={('Title', 'Year')},
        ),
        migrations.RemoveField(
            model_name='reelgood_load',
            name='Reelgood_Id',
        ),
    ]
