# Generated by Django 2.2.7 on 2019-12-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_ID', models.IntegerField()),
                ('User', models.TextField()),
                ('Score', models.IntegerField()),
            ],
            options={
                'unique_together': {('Movie_ID', 'User')},
            },
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
